spring.application.name=vetzone
server.port=8080

spring.thymeleaf.cache=false

# Esto es el MySQL local con variables de entorno y defaults
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/vetzonedb}
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 

# Internacionalizacion
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false